config/routes.rb
Ai::Application.routes.draw do
  
  controller :sessions do
    get 'login' => :login
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  root 'main#index', as: 'main'

  

end

app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, email: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :authorize
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
    def authorize
      puts session[:user_id]
      unless User.find_by_id(session[:user_id])
        redirect_to login_url, notice: "Пожалуйста пройдите авторизацию"
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_filter :authorize
  
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize
  
  def login
  end

  def create
    user = User.find_by_name(params[:name])

    if user and user.authenticate(params[:password])
      session[:user_name] = "#{user.lastname} #{user.firstname}"
      session[:user_id] = user.id
      redirect_to users_path
    else
      redirect_to login_url, alert: "Неверная комбинация имени и пароля"
    end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to main_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authorize, only: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html {
          redirect_to users_url,
          notice: "Пользователь #{@user.name} успешно создан"
        }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html {
          redirect_to users_url,
          notice: "Пользователь #{@user.name} успешно обновлен"
        }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :firstname, :lastname, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AiChallenge</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name%>">
  <span id="head">
  	<div class="left"></div>
  	<div class="center">
  		<%= image_tag("logo2.png") %>
		</div>
  	<div class="right"></div>
    <div class="line">
      <% if session[:user_id] %>
        <div class="user">
          <%= session[:user_name] %>
        </div>
        <%= button_to 'Logout', logout_path, method: :delete %>
      <% else %>
        <div class="button-group">
          <%= link_to 'Вход', login_path, {class: "button green"} %>
          <%= link_to 'Регистрация', new_user_path, {class: "button wood"} %>
        </div>
      <% end %>
    </div>
  </span>
  </div>
  <div id="columns">
  	<div id="side">
  		<ul>
  			<li><%= link_to 'Главная', main_path %></li>
				<li><a href="#">Как начать</a></li>
				<li><a href="#">Скриншоты</a></li>
				<li><a href="#">Правила</a></li>
				<li><a href="#">Примеры</a></li>
				<li><a href="#">Документация</a></li>
				<li><a href="#">Топ</a></li>
				<li><a href="#">Битвы</a></li>
				<li><a href="#">О нас</a></li>
  		</ul>
  	</div>
  	<div id="main"><%= yield %></div>
  </div>
</body>
</html>

app/views/main/index.html.erb
<h1>AiChallenge</h1>
<p>AI Challenge - это битва искусственных интеллектов, представленная в виде игры</p>
<p>Действие происходит в лесу, где армии муравьев, управляемые ИИ игроков, сражаются за господство над всем лесом.</p>
<p>Чтобы победить, нужно написать умный алгоритм, способный грамотно вести армию муравьев в бой и противостоять армиям других игроков</p>
<p>С 2 муравьев и до непобедимой армии! Управляй войсками, разделяй и властвуй. Начни завоевание леса!</p>

<%= link_to 'Users', users_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "errors") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Имя' %>:<br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label 'Пароль' %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label 'Повтор пароля' %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label 'Имя' %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label 'Фамилия' %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label 'Email' %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit 'Создать' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Пользователи</h1>
  <% if notice %>
    <p id="notice"><% notice %></p>
  <% end %>

<table>
  <thead>
    <tr>
      <th>Имя</th>
      <th>Имя</th>
      <th>Фамилия</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Информация', user %></td>
        <td><%= link_to 'Редактировать', edit_user_path(user) %></td>
        <td><%= link_to 'Удалить', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Новый пользователь</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>